package database

const (
	OpTypeVote                 = "vote"
	OpTypeComment              = "comment"
	OpTypeTransfer             = "transfer"
	OpTypeTransferToVesting    = "transfer_to_vesting"
	OpTypeWithdrawVesting      = "withdraw_vesting"
	OpTypeLimitOrderCreate     = "limit_order_create"
	OpTypeLimitOrderCancel     = "limit_order_cancel"
	OpTypeFeedPublish          = "feed_publish"
	OpTypeConvert              = "convert"
	OpTypeAccountCreate        = "account_create"
	OpTypeAccountUpdate        = "account_update"
	OpTypeWitnessUpdate        = "witness_update"
	OpTypeAccountWitnessVote   = "account_witness_vote"
	OpTypeAccountWitnessProxy  = "account_witness_proxy"
	OpTypePow                  = "pow"
	OpTypeCustom               = "custom"
	OpTypeReportOverProduction = "report_over_production"
	OpTypeFullConvertRequest   = "fill_convert_request"
	OpTypeCommentReward        = "comment_reward"
	OpTypeCurateReward         = "curate_reward"
	OpTypeLiquidityReward      = "liquidity_reward"
	OpTypeInterest             = "interest"
	OpTypeFillVestingWithdraw  = "fill_vesting_withdraw"
	OpTypeFillOrder            = "fill_order"
)
